#pragma once

/* Measured Radiolink R7FG positions used as compiled calibration defaults. */
#define DEFAULT_RC_THROTTLE_NEUTRAL_US 1514U
#define DEFAULT_RC_THROTTLE_FULL_US 978U
#define DEFAULT_RC_THROTTLE_REVERSE_US 2044U
#define DEFAULT_RC_THROTTLE_DEADBAND_US 80U
#define DEFAULT_RC_THROTTLE_FAILSAFE_ENABLED 0U
#define DEFAULT_RC_THROTTLE_FAILSAFE_US 1565U
#define DEFAULT_RC_THROTTLE_FAILSAFE_WINDOW_US 10U

#define DEFAULT_RC_STEERING_CENTER_US 1518U
#define DEFAULT_RC_STEERING_LEFT_US 2050U
#define DEFAULT_RC_STEERING_RIGHT_US 987U
#define DEFAULT_RC_STEERING_DEADBAND_US 30U

#define DEFAULT_RC_TV_OFF_US 2047U
#define DEFAULT_RC_TV_STRAIGHT_US 1513U
#define DEFAULT_RC_TV_FULL_US 981U

#define DEFAULT_RC_ARM_RUN_US 983U
#define DEFAULT_RC_ARM_STOP_1_US 2049U
#define DEFAULT_RC_ARM_STOP_2_US 1515U
#define DEFAULT_RC_ARM_POSITION_WINDOW_US 125U

/* Measured vehicle geometry and conservative initial cornering limits. */
#define DEFAULT_WHEEL_DIAMETER_M 0.107f
#define DEFAULT_WHEELBASE_M 0.445f
#define DEFAULT_TRACK_WIDTH_M 0.320f
#define DEFAULT_STEERING_SPEED_LIMIT_ENABLED 1U
#define DEFAULT_STEERING_LATERAL_ACCEL_G 1.0f
#define DEFAULT_TV_FRONT_RELIEF_PERCENT 20U

/* Physical IMU mounting reference; yaw polarity remains runtime-configurable. */
#define IMU_MOUNT_X_POSITIVE_DIRECTION "rearward"
#define IMU_MOUNT_Y_POSITIVE_DIRECTION "right"
